show_status = {
'Aborted_clients': 'gauge',
'Uptime': 'gauge',
'Questions': 'gauge',
'Uptime_since_flush_status': 'gauge',
'Threads_running': 'gauge',
'Threads_created': 'gauge',
'Threads_connected': 'gauge',
'Threads_cached': 'gauge',
'Table_locks_waited': 'gauge',
'Table_locks_immediate': 'gauge',
'Sort_scan': 'gauge',
'Sort_rows': 'gauge',
'Sort_range': 'gauge',
'Sort_merge_passes': 'gauge',
'Slow_queries': 'gauge',
'Slow_launch_threads': 'gauge',
'Select_scan': 'gauge',
'Select_range_check': 'gauge',
'Select_range': 'gauge',
'Select_full_range_join': 'gauge',
'Select_full_join': 'gauge',
'Queries': 'gauge',
'Qcache_total_blocks': 'gauge',
'Qcache_queries_in_cache': 'gauge',
'Qcache_not_cached': 'gauge',
'Qcache_lowmem_prunes': 'gauge',
'Qcache_inserts': 'gauge',
'Qcache_hits': 'gauge',
'Qcache_free_memory': 'gauge',
'Qcache_free_blocks': 'gauge',
'Prepared_stmt_count': 'gauge',
'Performance_schema_thread_instances_lost': 'gauge',
'Performance_schema_thread_classes_lost': 'gauge',
'Performance_schema_table_instances_lost': 'gauge',
'Performance_schema_table_handles_lost': 'gauge',
'Performance_schema_rwlock_instances_lost': 'gauge',
'Performance_schema_rwlock_classes_lost': 'gauge',
'Performance_schema_mutex_instances_lost': 'gauge',
'Performance_schema_mutex_classes_lost': 'gauge',
'Performance_schema_locker_lost': 'gauge',
'Performance_schema_file_instances_lost': 'gauge',
'Performance_schema_file_handles_lost': 'gauge',
'Performance_schema_file_classes_lost': 'gauge',
'Performance_schema_cond_instances_lost': 'gauge',
'Performance_schema_cond_classes_lost': 'gauge',
'wsrep_cluster_size': 'gauge',
'wsrep_cert_index_size': 'gauge',
'wsrep_local_send_queue': 'gauge',
'wsrep_local_replays': 'gauge',
'wsrep_local_bf_aborts': 'gauge',
'wsrep_local_cert_failures': 'gauge',
'wsrep_local_commits': 'gauge',
'wsrep_received_bytes': 'gauge',
'wsrep_received': 'gauge',
'wsrep_replicated_bytes': 'gauge',
'wsrep_replicated': 'gauge'
}

show_engine_status = (
'mutex_spin_waits',
)
